### ISSUE TITLE
am2svg fails if the last "math" argument starts with a minus (dash) character

### ISSUE THREAD

**Issue by garagebrewer** [mathjax/mathjax-node-cli#12]
Using the command line am2svg --font STIX --speech false '-sqrt3'

...fails because the last argument appears to be an option to the command.

I used to be able to pass a -- before the last argument and it worked but that fails now.  I suspect it's an issue with yargs and used to be handled differently.

**Comment by dpvc** [comment]
Hmm, 

   am2svg --font STIX --speech false -- '-sqrt3'

works for me.  Can you you verify that this doesn't work for you?  Can you also try

   node  am2svg --font STIX --speech false -- '-sqrt3'

If these don't work, can you tell me the OS you are using?

**Comment by garagebrewer** [comment]
I am having trouble on both Linux Mint 19.1 and Mac OS Catalina (homebrew
installed).

I very recently set these computers both up, so it seems new with some new
version of Node or of some dependency or with am2svg.  Not sure but this
used to work until I upgraded software.

npm -v mathjax-node-cli
...reports as 3.5.2

--Phil

**Comment by dpvc** [comment]
I get 6.13.6 for `npm -v` (I don't think it takes an argument), which is the npm version, so it seems you may be a bit out of date with that.  For `node -v` I get `v10.15.1`.  For `npm version`, I get

```
{ 'mathjax-node-cli': '1.0.1',
  npm: '6.13.6',
  ares: '1.15.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.1',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.12',
  zlib: '1.2.11' }
```

**Comment by garagebrewer** [comment]
Sorry, I am not a node person.  Java mostly.

I get this:
{ 'mathjax-node-cli': '1.0.1',
  npm: '3.5.2',
  ares: '1.14.0',
  cldr: '32.0.1',
  http_parser: '2.7.1',
  icu: '60.2',
  modules: '57',
  nghttp2: '1.30.0',
  node: '8.10.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.50',
  zlib: '1.2.11' }

...so do you think I need up upgrade node?

**Comment by dpvc** [comment]
I'd start with updating npm, using

    npm install -g npm

or

    sudo npm install -g npm

on your Mac.  Then do

    npm install

again in the mathjax-node-cli directory and see if you get new versions of anything.

Then if that doesn't work, try updating node itself.  See [this site](https://www.hostingadvice.com/how-to/update-node-js-latest-version) for details.

**Comment by garagebrewer** [comment]
Well, that version info I gave you was from my linux machine.  On my mac, I
had quite different version info.  I went ahead and upgraded and I still
have the same trouble.  Here is my version info now on the Mac:

{
  'mathjax-node-cli': '1.0.1',
  npm: '6.13.6',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  icu: '64.2',
  llhttp: '2.0.1',
  modules: '79',
  napi: '5',
  nghttp2: '1.40.0',
  node: '13.7.0',
  openssl: '1.1.1d',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.34.1',
  v8: '7.9.317.25-node.28',
  zlib: '1.2.11'
}

The output of the command is this:
% am2svg --font STIX --speech false -- '-sqrt3'
am2svg [options] 'math' > file.svg

Options:
  --help        Show help
 [boolean]
  --version     Show version number
 [boolean]
  --linebreaks  perform automatic line-breaking        [boolean] [default:
true]
  --speech      include speech text
 [boolean]
  --font        web font to use                                 [default:
"TeX"]
  --ex          ex-size in pixels
[default: 6]
  --width       width of container in ex                          [default:
100]
  --extensions  extra MathJax extensions e.g. 'Safe,TeX/noUndefined'

 [default: ""]

Not enough non-option arguments: got 0, need at least 1

**Comment by garagebrewer** [comment]
I tested various other commands to see if my system fails on "--" elsewhere
and it does not.  "--" works fine and is supported by my shell (zsh on the
Mac).

I have resolved the issue by commenting out this line:
//.demand(1).strict()

Now it works fine with the double-dash parameter.

I hope this helps.

--Phil

**Comment by dpvc** [comment]
OK, thanks for the work-around.  I still don't understand why it doesn't work for you but does for me.  Most peculiar.
