### ISSUE TITLE
Question: Can I use mathjaxcli to convert html -> html

### ISSUE THREAD

**Issue by tinmarino** [mathjax/mathjax-node-cli#13]
Hello,

Not an issue, just a question.
MathJax is awesome very good work.
This CLI is what I was looking for. I want a one file standalone html output.

I love the output of the CLI. But the input seems to be a well formatted string ML.
I wonder how I can dirtily give all my html in input, maybe making a script in my Makefile to exctract the $texts$. I don't even know how MathJax.js is doing it. 

I am a pure nooby in JS, really not comfortable but I like to use your tool because it is a one liner to get all LaTeX power.
Thanks for the great job and feel free to close at anytime.

**Comment by tinmarino** [comment]
My bad, the answer was just the next line on [MathJax-node](https://github.com/mathjax/MathJax-node) and it is called [MathJax-node-page](https://github.com/pkra/mathjax-node-page/).
```
Usage: mjpage [options] < input.html > output.html
```
Once again awesome team work guys.

**Comment by dpvc** [comment]
Note that mathjax-node is an interface to MathJax v2, which was not designed to work with node, and so is a bit of a hack.  MathJax version 3 (a redesign of MathJax from the ground up) had node support in mind form the beginning, so it is much easier to work with v3 in node directly.  See the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) repository for some examples.  See the [MathJax documentation](http://docs.mathjax.org/en/latest/index.html) for general information about MathJax v3.

**Comment by tinmarino** [comment]
OK so it is tex2chtml-page for me from mathjax demo node directly, meaning __without__ the mathjax-node-page.
My bad, I am so bad in js that I did not know where the executables got installed.
