### ISSUE TITLE
Newer SVG options are not exposed; such as blacker

### ISSUE THREAD

**Issue by stroobandt** [mathjax/mathjax-node-cli#15]
[Newer MathJax SVG options](https://docs.mathjax.org/en/v2.7-latest/options/output-processors/SVG.html) are not exposed.

Especially the SVG option `blacker`, [would be very useful](https://www.princexml.com/forum/topic/4116/svg-output-differs-between-browser-and-prince) to have in `tex2svg`.

**Comment by stroobandt** [comment]
I saw that `mathjax-node-cli` uses `mathjax-node-sre` under the bonnet.

The good news is that [`mathjax-node-sre` already supports these newer SVG options](https://github.com/pkra/mathjax-node-sre/issues/49); such as the `blacker` option.

**Comment by dpvc** [comment]
As with `mathjax-node-sre`, these options are available through the `MathJax` section of the configuration object that you can pass to `mathjax-node`.  They are not available directly on the command line, but can be set in the configuration.  The cli commands are meant as examples to be modified as needed for your specific situation, so you can change

https://github.com/mathjax/mathjax-node-cli/blob/412daef35f26a963e178e25bc8d87a2ba3985aae/bin/tex2svg#L65

to be

``` jsvascript
mjAPI.config({
  MathJax: {
    SVG: {
      font: argv.font,
      blacker: 0
    }
  },
  extensions: argv.extensions
});
```

to include blacker, or you could add your own command-line arguments to be able to pass the value into it, like the font value currently is.  Just to be clear, that is how `mathjax-node-sre` "supports" it as well.
