### ISSUE TITLE
Please be aware travis-ci.org will be shutting down in several weeks

### ISSUE THREAD

**Issue by stroobandt** [mathjax/mathjax-node-cli#17]
> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

Other projects on GitHub are migrating to Docker.
See for example: https://github.com/pandoc/lua-filters/blob/master/.tools/Dockerfile

**Comment by dpvc** [comment]
Thanks for the comment; because of it, I have been investigating our options.  We are already migrating to travis-ci.com, and the imminent 3.1.3 release will be a test of whether that has worked for us.
